name: Test Calculator

on:
  push:
    branches: 
      - master  # Trigger on push to the master branch
  pull_request:
    branches: 
      - master  # Trigger on pull request to the master branch
    
jobs:
  test:
    runs-on: ubuntu-latest  # This specifies the environment for the job

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your Python version if needed (e.g., '3.8')

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust if you don't use external dependencies

      # Step 4: Run tests using unittest discover (runs all tests in your repo)
      - name: Run tests
        run: |
          python -m unittest discover -s tests -p "*.py"  # Adjust if your test folder is named differently or you have other patterns

  deploy:
    needs: test  # This job will only run if the test job is successful
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository for deployment
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Deploy Application (replace with actual deployment steps)
      - name: Deploy Application
        run: |
          echo "Deploying the application..."
          # Example deployment command; replace with actual logic
          # e.g., AWS, Docker, Heroku, or your deployment platform commands
