name: Test Calculator

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  test:
    runs-on: ubuntu-latest  # Replace with desired runner OS (e.g., macOS, Windows)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the repository code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Replace with your Python version (adjust if needed)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Ensure pip is up-to-date
          pip install -r requirements.txt || echo "No requirements.txt found"  # Install dependencies (if any)

      - name: Run tests
        run: |
          export PYTHONPATH=$(pwd)  # Ensure the current directory is in the Python path
          python -m unittest discover -s . -p "test_*.py"  # Discover and run all tests matching 'test_*.py'

