name: Test Calculator

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  test:
    runs-on: ubuntu-latest  # This specifies the OS for the job, you can change this to macOS or Windows if needed.

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This step checks out your code from GitHub

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Adjust Python version if needed, you can specify like '3.8' if you want a specific version.

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Ensures pip is updated
          pip install -r requirements.txt || echo "No requirements.txt found"  # Install dependencies (if requirements.txt exists)

      - name: Run tests
        run: |
          python -m unittest discover -s . -p "test_*.py"  # This will discover and run all test files matching the pattern 'test_*.py'

  deploy:
    needs: test  # This job will run only if the 'test' job passes
    runs-on: ubuntu-latest  # Use the same runner, or change it if needed for deployment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Application
        run: |
          echo "Deploying the application..."  # Replace this with your actual deployment commands.
